// Code generated by "stringer -type SheetType -trimprefix SheetType"; DO NOT EDIT.

package excel

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SheetTypeUnknown-0]
	_ = x[SheetTypeNormal-1]
	_ = x[SheetTypeTOC-2]
	_ = x[SheetTypeCover-3]
}

const _SheetType_name = "UnknownNormalTOCCover"

var _SheetType_index = [...]uint8{0, 7, 13, 16, 21}

func (i SheetType) String() string {
	if i < 0 || i >= SheetType(len(_SheetType_index)-1) {
		return "SheetType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SheetType_name[_SheetType_index[i]:_SheetType_index[i+1]]
}
